// import hpeConfig from 'design-tokens/dist/tailwind/tailwind.config.js';

/** @type {import('tailwindcss').Config} */
export default {
  mode: 'jit',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: [
          // TO DO create fontStack token
          'Metric',
          'ui-sans-serif',
          'system-ui',
        ],
      },
      colors: {
        background: {
          default: 'var(--hpe-color-background-default)',
          hover: 'var(--hpe-color-background-hover)',
          active: 'var(--hpe-color-background-active)',
          disabled: 'var(--hpe-color-background-disabled)',
          back: 'var(--hpe-color-background-back)',
          front: 'var(--hpe-color-background-front)',
          raised: 'var(--hpe-color-background-raised)',
          floating: 'var(--hpe-color-background-floating)',
          contrast: 'var(--hpe-color-background-contrast)',
          validation: {
            info: 'var(--hpe-color-background-validation-info)',
            warning: 'var(--hpe-color-background-validation-warning)',
            unknown: 'var(--hpe-color-background-validation-unknown)',
            critical: 'var(--hpe-color-background-validation-critical)',
            ok: 'var(--hpe-color-background-validation-ok)',
          },
          selected: {
            strong: 'var(--hpe-color-background-selected-strong)',
            weak: 'var(--hpe-color-background-selected-weak)',
          },
          primary: {
            default: 'var(--hpe-color-background-primary-default)',
            hover: 'var(--hpe-color-background-primary-hover)',
          },
        },
        border: {
          strong: 'var(--hpe-color-border-strong)',
          default: 'var(--hpe-color-border-default)',
          weak: 'var(--hpe-color-border-weak)',
          disabled: 'var(--hpe-color-border-disabled)',
          selected: 'var(--hpe-color-border-selected)',
        },
        text: {
          default: 'var(--hpe-color-text-default)',
          strong: 'var(--hpe-color-text-strong)',
          weak: 'var(--hpe-color-text-weak)',
          xweak: 'var(--hpe-color-text-xweak)',
          disabled: 'var(--hpe-color-text-disabled)',
          critical: 'var(--hpe-color-text-critical)',
          info: 'var(--hpe-color-text-info)',
          ok: 'var(--hpe-color-text-ok)',
          warning: 'var(--hpe-color-text-warning)',
          unknown: 'var(--hpe-color-text-unknown)',
          onPrimary: 'var(--hpe-color-text-on-primary)',
          brand: 'var(--hpe-color-text-brand)',
        },
      },
      borderRadius: {
        none: 'var(--hpe-radius-none)',
        hair: 'var(--hpe-radius-hair)',
        xxsmall: 'var(--hpe-radius-xxsmall)',
        xsmall: 'var(--hpe-radius-xsmall)',
        small: 'var(--hpe-radius-small)',
        medium: 'var(--hpe-radius-medium)',
        large: 'var(--hpe-radius-large)',
        xlarge: 'var(--hpe-radius-xlarge)',
      },
      borderWidth: {
        none: 'var(--hpe-border-none)',
        hair: 'var(--hpe-border-hair)',
        xxsmall: 'var(--hpe-border-xxsmall)',
        xsmall: 'var(--hpe-border-xsmall)',
        small: 'var(--hpe-border-small)',
        medium: 'var(--hpe-border-medium)',
        large: 'var(--hpe-border-large)',
        xlarge: 'var(--hpe-border-xlarge)',
      },
      fontSize: {
        base: [
          'var(--hpe-text-medium-font-size)',
          { lineHeight: 'var(--hpe-text-medium-line-height)' },
        ],
        xsmall: [
          'var(--hpe-text-xsmall-font-size)',
          { lineHeight: 'var(--hpe-text-xsmall-line-height)' },
        ],
        small: [
          'var(--hpe-text-small-font-size)',
          { lineHeight: 'var(--hpe-text-small-line-height)' },
        ],
        medium: [
          'var(--hpe-text-medium-font-size)',
          { lineHeight: 'var(--hpe-text-medium-line-height)' },
        ],
        large: [
          'var(--hpe-text-large-font-size)',
          { lineHeight: 'var(--hpe-text-large-line-height)' },
        ],
        xlarge: [
          'var(--hpe-text-xlarge-font-size)',
          { lineHeight: 'var(--hpe-text-xlarge-line-height)' },
        ],
        xxlarge: [
          'var(--hpe-text-xxlarge-font-size)',
          { lineHeight: 'var(--hpe-text-xxlarge-line-height)' },
        ],
        '3xl': [
          'var(--hpe-text-3xl-font-size)',
          { lineHeight: 'var(--hpe-text-3xl-line-height)' },
        ],
        '4xl': [
          'var(--hpe-text-4xl-font-size)',
          { lineHeight: 'var(--hpe-text-4xl-line-height)' },
        ],
        '5xl': [
          'var(--hpe-text-5xl-font-size)',
          { lineHeight: 'var(--hpe-text-5xl-line-height)' },
        ],
        '6xl': [
          'var(--hpe-text-6xl-font-size)',
          { lineHeight: 'var(--hpe-text-6xl-line-height)' },
        ],
      },
      spacing: {
        none: 'var(--hpe-spacing-none)',
        hair: 'var(--hpe-spacing-hair)',
        xxsmall: 'var(--hpe-spacing-xxsmall)',
        xsmall: 'var(--hpe-spacing-xsmall)',
        small: 'var(--hpe-spacing-small)',
        medium: 'var(--hpe-spacing-medium)',
        large: 'var(--hpe-spacing-large)',
        xlarge: 'var(--hpe-spacing-xlarge)',
      },
      screens: {
        xsmall: 'var(--hpe-base-breakpoint-xsmall)',
        small: 'var(--hpe-base-breakpoint-small)',
        medium: 'var(--hpe-base-breakpoint-medium)',
        large: 'var(--hpe-base-breakpoint-large)',
      },
      height: {
        xxsmall: 'var(--hpe-content-xxsmall)',
        xsmall: 'var(--hpe-content-xsmall)',
        small: 'var(--hpe-content-small)',
        medium: 'var(--hpe-content-medium)',
        large: 'var(--hpe-content-large)',
        xlarge: 'var(--hpe-content-xlarge)',
        xxlarge: 'var(--hpe-content-xxlarge)',
      },
      maxHeight: {
        xxsmall: 'var(--hpe-content-xxsmall)',
        xsmall: 'var(--hpe-content-xsmall)',
        small: 'var(--hpe-content-small)',
        medium: 'var(--hpe-content-medium)',
        large: 'var(--hpe-content-large)',
        xlarge: 'var(--hpe-content-xlarge)',
        xxlarge: 'var(--hpe-content-xxlarge)',
      },
      minHeight: {
        xxsmall: 'var(--hpe-content-xxsmall)',
        xsmall: 'var(--hpe-content-xsmall)',
        small: 'var(--hpe-content-small)',
        medium: 'var(--hpe-content-medium)',
        large: 'var(--hpe-content-large)',
        xlarge: 'var(--hpe-content-xlarge)',
        xxlarge: 'var(--hpe-content-xxlarge)',
      },
      maxWidth: {
        xxsmall: 'var(--hpe-content-xxsmall)',
        xsmall: 'var(--hpe-content-xsmall)',
        small: 'var(--hpe-content-small)',
        medium: 'var(--hpe-content-medium)',
        large: 'var(--hpe-content-large)',
        xlarge: 'var(--hpe-content-xlarge)',
        xxlarge: 'var(--hpe-content-xxlarge)',
      },
      minWidth: {
        xxsmall: 'var(--hpe-content-xxsmall)',
        xsmall: 'var(--hpe-content-xsmall)',
        small: 'var(--hpe-content-small)',
        medium: 'var(--hpe-content-medium)',
        large: 'var(--hpe-content-large)',
        xlarge: 'var(--hpe-content-xlarge)',
        xxlarge: 'var(--hpe-content-xxlarge)',
      },
      width: {
        xxsmall: 'var(--hpe-content-xxsmall)',
        xsmall: 'var(--hpe-content-xsmall)',
        small: 'var(--hpe-content-small)',
        medium: 'var(--hpe-content-medium)',
        large: 'var(--hpe-content-large)',
        xlarge: 'var(--hpe-content-xlarge)',
        xxlarge: 'var(--hpe-content-xxlarge)',
      },
    },
  },
};
