packages:
  - 'aries-core'
  - 'aries-site'
  - 'packages/*'
  - 'sandbox/*'
  - 'design-tokens-manager'
  - 'design-tokens'
  - 'shared/*'

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  styled-components: ^6.1.17
  prop-types: ^15.8.1
  grommet-theme-hpe: ^8.0.0
  grommet: ^2.51.0
  grommet-icons: ^4.14.0
  "@hpe-design/icons-grommet": ^1.0.1
  "@types/react": ^19.1.10
  "@types/react-dom": ^19.1.7

catalogs:
  grommet-stable:
    grommet: https://github.com/grommet/grommet/tarball/stable
    grommet-icons: https://github.com/grommet/grommet-icons/tarball/stable
  
  grommet-theme-hpe-v5:
    grommet-theme-hpe: npm:grommet-theme-hpe@5.8.0
  
  grommet-theme-hpe-v6:
    grommet-theme-hpe: npm:grommet-theme-hpe@6
  
  grommet-theme-hpe-v7:
    grommet-theme-hpe: ^7.0.0
