packages:
  - 'apps/*'
  - 'aries-site'
  - 'packages/**'
  - 'sandbox/*'
  - 'shared/*'

catalog:
  '@hpe-design/icons-grommet': ^1.1.0
  '@types/node': ^20.4.5
  '@types/react': ^19.1.10
  '@types/react-dom': ^19.1.7
  eslint: ^8.39.0
  grommet: ^2.51.0
  grommet-icons: ^4.14.0
  grommet-theme-hpe: ^8.0.0
  prop-types: ^15.8.1
  react: ^19.2.3
  react-dom: ^19.2.3
  styled-components: ^6.1.17
  typescript: ^5.9.3

catalogs:
  grommet-stable:
    grommet: https://github.com/grommet/grommet/tarball/stable
    grommet-icons: https://github.com/grommet/grommet-icons/tarball/stable
  grommet-theme-hpe-v6:
    grommet-theme-hpe: ^6.0.0
  grommet-theme-hpe-v7:
    grommet-theme-hpe: ^7.0.0
