import {
  Beacon,
  Server,
  StatusCritical,
  StatusGood,
  StatusWarning,
  Switch,
  Technology,
} from 'grommet-icons';

export const data = [
  {
    displayName: 'Michael Walsh',
    alias: 'Mikey',
    cardColor: 'blue',
    emailAddress: 'michael.walsh@hpe.com',
    icon: (color, size) => <Beacon color={color} size={size} />,
    location: 'Astoria',
    deviceName: 'P1-K-24',
    ipAddress: '66.168.13.8',
    imageUrl:
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2389&q=80',
    status: {
      value: 'status-ok',
      message: 'ok',
      icon: (color, size) => <StatusGood color={color} size={size} />,
    },
    type: 'Access Point',
  },
  {
    displayName: 'Troy Perkins',
    alias: 'Troy',
    cardColor: 'red',
    emailAddress: 'troy.perkins@hpe.com',
    icon: (color, size) => <Technology color={color} size={size} />,
    location: 'Fort Collins',
    deviceName: '4L-D2-C3',
    ipAddress: '66.171.153.8',
    imageUrl:
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2389&q=80',
    status: {
      value: 'status-ok',
      message: 'ok',
      icon: (color, size) => <StatusGood color={color} size={size} />,
    },
  },
  {
    displayName: 'Lawrence Cohen',
    alias: 'Chunk',
    cardColor: 'red',
    emailAddress: 'lawrence.cohen@hpe.com',
    icon: (color, size) => <Technology color={color} size={size} />,
    location: 'Fort Collins',
    deviceName: '4L-D2-C3',
    ipAddress: '192.168.1.1',
    imageUrl:
      'https://images.unsplash.com/photo-1456049616707-070399496327?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3300&q=80',
    status: {
      value: 'status-critical',
      message: 'critical',
      icon: (color, size) => <StatusCritical color={color} size={size} />,
    },
  },
  {
    displayName: 'Andrea Carmichael',
    alias: 'Andy',
    cardColor: 'blue',
    emailAddress: 'andrea.carmichael@hpe.com',
    icon: (color, size) => <Beacon color={color} size={size} />,
    location: 'Fort Collins',
    deviceName: '6U-T-14',
    ipAddress: '192.168.15.105',
    imageUrl:
      'https://images.unsplash.com/photo-1456049616707-070399496327?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3300&q=80',
    status: {
      value: 'status-warning',
      message: 'warning',
      icon: (color, size) => <StatusWarning color={color} size={size} />,
    },
    type: 'Access Point',
  },
  {
    displayName: 'Richard Wang',
    alias: 'Data',
    cardColor: 'green',
    emailAddress: 'richard.wang@hpe.com',
    icon: (color, size) => <Server color={color} size={size} />,
    location: 'Fort Collins',
    deviceName: '6L-RS-T3',
    ipAddress: '192.168.13.7',
    imageUrl:
      'https://images.unsplash.com/photo-1503424886307-b090341d25d1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1955&q=80',
    status: {
      value: 'status-warning',
      message: 'warning',
      icon: (color, size) => <StatusWarning color={color} size={size} />,
    },
    type: 'Server',
  },
  {
    displayName: 'Clark Devereaux',
    alias: 'Mouth',
    cardColor: 'orange',
    emailAddress: 'clark.devereaux@hpe.com',
    icon: (color, size) => <Switch color={color} size={size} />,
    location: 'Fort Collins',
    deviceName: '4L-S2-T57',
    ipAddress: '192.168.15.46',
    imageUrl:
      'https://images.unsplash.com/photo-1503424886307-b090341d25d1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1955&q=80',
    status: {
      value: 'status-ok',
      message: 'ok',
      icon: (color, size) => <StatusGood color={color} size={size} />,
    },
    type: 'Switch',
  },
  {
    displayName: 'Chester Copperpot',
    alias: undefined,
    cardColor: 'blue',
    emailAddress: 'chester.copperpot@hpe.com',
    icon: (color, size) => <Beacon color={color} size={size} />,
    location: 'Fort Collins',
    deviceName: 'P2-L-18',
    ipAddress: '66.168.13.4',
    imageUrl:
      'https://images.unsplash.com/photo-1503424886307-b090341d25d1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1955&q=80',
    status: {
      value: 'status-ok',
      message: 'ok',
      icon: (color, size) => <StatusGood color={color} size={size} />,
    },
    type: 'Access Point',
  },
  {
    displayName: 'Mamma Fratelli',
    alias: undefined,
    cardColor: 'blue',
    emailAddress: 'mamma.fratelli@hpe.com',
    icon: (color, size) => <Beacon color={color} size={size} />,
    location: 'Fort Collins',
    deviceName: '6U-T-12',
    ipAddress: '192.168.15.100',
    imageUrl:
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2389&q=80',
    status: {
      value: 'status-ok',
      message: 'ok',
      icon: (color, size) => <StatusGood color={color} size={size} />,
    },
    type: 'Access Point',
  },
  {
    displayName: 'Brandon Walsh',
    alias: 'Brand',
    cardColor: 'blue',
    emailAddress: 'brandon.walsh@hpe.com',
    icon: (color, size) => <Beacon color={color} size={size} />,
    location: 'Fort Collins',
    deviceName: '6U-T-13',
    ipAddress: '192.168.15.101',
    imageUrl:
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2389&q=80',
    status: {
      value: 'status-ok',
      message: 'ok',
      icon: (color, size) => <StatusGood color={color} size={size} />,
    },
    type: 'Access Point',
  },
  {
    displayName: 'Stephanie Steinbrenner',
    alias: 'Stef',
    cardColor: 'orange',
    emailAddress: 'stephanie.steinbrenner@hpe.com',
    icon: (color, size) => <Switch color={color} size={size} />,
    location: 'Fort Collins',
    deviceName: '4L-S2-D32',
    ipAddress: '192.168.15.24',
    imageUrl:
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2389&q=80',
    status: {
      value: 'status-ok',
      message: 'ok',
      icon: (color, size) => <StatusGood color={color} size={size} />,
    },
    type: 'Switch',
  },
];
