name: Figma Bug Report
description: Create a bug report for the HPE Design System Figma library.
title: "[Figma bug]: <title that includes component name>"
labels: [bug, design]
body:
- type: markdown
   attributes:
     value: Thank you for catching a bug in our Figma library! Please fill this form out as completely as possible to help us troubleshoot.
- type: input
  attributes:
    label: Link to bug
    description: Please link to the most specific file, section of file, or element as possible.
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Screenshot or recording of bug
    description: |
      You can attach images or files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1.
      2.
      3. 
  validations:
    required: false
