name: New
description: Request a new component, feature, or capability
title: 'New: <insert title>'
body:
  - type: input
    attributes:
      label: What does this request relate to? If you are proposing a new component, what would you call it?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Links to Figma files with use cases or ideations from you.
      description: Use cases and ideations help us understand the problem space. Please provide specific use cases when possible, and if you have any ideas or proposals we'd love to look at those too.
    validations:
      required: false
