name: Figma Feature Request
description: File a feature request for the HPE Design System Figma library
title: 'Figma feature: <insert title>'
labels: [design]
body:
  - type: input
    attributes:
      label: What component does this request relate to?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Links to Figma files with use cases or ideations from you.
      description: Use cases and ideations help us understand the problem space. Please provide specific use cases when possible, and if you have any ideas or proposals we'd love to look at those too.
    validations:
      required: false
