name: Design System Example Bug Report
description: Create a bug report for an example on the HPE Design System website
title: 'Site Example bug: <insert title>'
labels: [bug, design system site]
body:
  - type: input
    attributes:
      label: Link to bug
      description: Please link to the subsection of page if possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshot or recording of bug
      description: |
        You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false
