name: Design System Documentation Request
description: Create a request to update or improve guidance and/or examples
title: "[Documentation request] <title>"
labels: [design-system-site]
body:
- type: textarea
  attributes:
    label: What is the improvement or addition you'd like to see?
    description: 'Example: I would like to see an example of how to build an accessible form. OR I would like more guidance on when to use a side drawer layer.'
  validations:
    required: true
- type: textarea
  attributes:
    label: Can you describe any use cases driving your request?
    description: Use cases help us to better understand the problem space and build realistic examples. Feel free to include links to files if you have any to share.
  validations:
    required: false
