blank_issues_enabled: true
contact_links:
  - name: Ask a question in hpe-design-system Slack
    url: https://slack-invite.grommet.io/
    about: Ask questions and discuss with others when you sign up for Grommet Slack with your HPE email.
