export default {
  Accessibility: [
    'body',
    'disabled',
    'disability',
    'human',
    'person',
    'accessibility',
  ],
  Achievement: ['award', 'medal', 'prize', 'trophy', 'winner', 'achievement'],
  Actions: ['gear', 'sun', 'actions', 'tasks', 'operations'],
  Ad: ['advert', 'promotion', 'marketing', 'banner', 'announcement'],
  Add: ['create', 'core', 'increase', 'increment', 'new', 'plus'],
  Aed: ['cpr', 'defibrillator', 'emergency', 'heart', 'medical', 'shock'],
  Aggregate: ['add', 'combination', 'combine', 'join', 'merge', 'aggregate'],
  AIGen: ['AI', 'artificial intelligence', 'LLM'],
  AIGenFill: ['AI', 'artificial intelligence', 'LLM', 'filled', 'solid'],
  AISystems: [
    'ai',
    'artificial intelligence',
    'systems',
    'automation',
    'machine learning',
  ],
  Aid: [
    'briefcase',
    'care',
    'emergency',
    'first-aid',
    'first aid kit',
    'health',
  ],
  Alarm: ['alert', 'alarmclock', 'bell', 'clock', 'hands', 'time'],
  Alert: ['alert', 'status', 'validation'],
  Analytics: ['chart', 'diagram', 'dontusepies', 'graph', 'pie', 'report'],
  Anchor: ['anchor', 'link'],
  Announce: ['bullhorn', 'loud', 'speaker', 'megaphone', 'announce'],
  App: ['app', 'application', 'software', 'program', 'tool'],
  Apps: ['grid', 'menu', 'apps', 'applications', 'software'],
  Archive: ['backup', 'box', 'container', 'document', 'files', 'folder'],
  Article: ['blog', 'news', 'newspaper', 'press', 'article'],
  Ascend: ['arrange', 'arrows', 'sort', 'up', 'ascend'],
  Ascending: ['arrange', 'arrows', 'sort', 'up', 'ascending'],
  AssistListening: ['accessibility', 'audio', 'ear', 'hear', 'sound', 'assist'],
  Atm: ['bank', 'card', 'credit', 'cash', 'finance', 'money'],
  Attachment: ['clip', 'files', 'paper', 'paperclip', 'attachment'],
  Attraction: [
    'amusement',
    'carnival',
    'circus',
    'festival',
    'tent',
    'attraction',
  ],
  Baby: ['child', 'diaper', 'kid', 'newborn', 'person', 'baby'],
  BackTen: ['arrows', 'backward', 'rewind', 'player', 'seconds', 'skip'],
  Bar: ['beer', 'cocktail', 'drink', 'glass', 'party', 'bar'],
  Battery: ['battery', 'capacity', 'medium', 'charge'],
  BatteryEmpty: ['battery', 'capacity', 'empty', 'charge'],
  BatteryFull: ['battery', 'capacity', 'full', 'charge'],
  BatteryLow: ['battery', 'capacity', 'low', 'charge'],
  Beacon: ['direction', 'guidance', 'technology', 'beacon'],
  Bike: ['bicycle', 'cycle', 'sport', 'transportation', 'bike'],
  BladesHorizontal: ['technology', 'blades', 'horizontal', 'landscape'],
  BladesVertical: ['technology', 'blades', 'vertical', 'upright'],
  Blog: ['blog', 'article', 'post', 'writing', 'journal'],
  Bluetooth: ['wire', 'wireless', 'hardware', 'bluetooth'],
  Book: ['education', 'learning', 'reading', 'study', 'book'],
  Bookmark: ['document', 'bookmark'],
  Braille: ['accessibility', 'blind', 'braille', 'tactile'],
  Briefcase: ['luggage', 'travel', 'briefcase', 'business', 'work'],
  Brush: ['tools', 'paint', 'brush', 'edit'],
  Bucket: ['bucket', 'container', 'storage', 'pail', 'collect'],
  Bug: ['fixing', 'insect', 'repair', 'virus', 'bug'],
  Bulb: [
    'bulb',
    'light',
    'lamp',
    'electricity',
    'illumination',
    'innovation',
    'idea',
    'eureka',
  ],
  Bundle: ['storage', 'box', 'modular', 'holding', 'unit', 'container'],
  Bus: ['directions', 'transportation', 'travel', 'vehicle', 'bus'],
  BusinessService: ['briefcase', 'services', 'business', 'service', 'workflow'],
  Cafeteria: ['cafe', 'dining', 'food', 'fork', 'meal', 'restaurant'],
  Calculator: ['adding machine', 'accounting', 'math', 'calculator'],
  Calendar: ['calendar', 'appointment', 'date', 'day', 'event', 'plan'],
  Camera: ['Camera', 'photo', 'phototgraphy'],
  Car: ['auto', 'directions', 'transportation', 'vehicle', 'car'],
  CaretDown: ['arrows', 'core', 'direction', 'down', 'expand', 'caret'],
  CaretLeft: ['arrows', 'core', 'direction', 'rewind', 'left', 'caret'],
  CaretRight: ['arrows', 'core', 'direction', 'forward', 'right', 'caret'],
  CaretUp: ['arrows', 'collapse', 'core', 'direction', 'up', 'caret'],
  Cart: ['buy', 'checkout', 'ecommerce', 'shopping', 'cart'],
  Catalog: ['catalogue', 'book', 'directory', 'document', 'index', 'catalog'],
  Certificate: [
    'license',
    'miscellaneous',
    'certificate',
    'credential',
    'award',
  ],
  Channel: [
    'communications',
    'media',
    'network',
    'tv',
    'television',
    'channel',
  ],
  ChapterAdd: ['add', 'create', 'new', 'plus', 'chapter'],
  ChapterNext: ['arrows', 'forward', 'chapter', 'next', 'navigation'],
  ChapterPrevious: ['arrows', 'backward', 'chapter', 'previous', 'navigation'],
  ChartBar: ['analytics', 'business', 'chart', 'graph', 'diagram'],
  ChartLine: ['graph', 'grow', 'time', 'chart'],
  ChartPie: ['analytics', 'dontusepies', 'graph', 'chart'],
  Chat: ['bubble', 'conversation', 'communication', 'core', 'help', 'messages'],
  ChatConversation: [
    'bubble',
    'conversation',
    'communication',
    'core',
    'help',
    'messages',
  ],
  Checkmark: ['accept', 'agree', 'core', 'done', 'good', 'ok'],
  CircleEmpty: ['chart', 'donut', 'circle', 'outline', 'radio'],
  CircleFill: ['chart', 'donut', 'circle', 'filled', 'radio'],
  Clear: ['forbidden', 'no', 'prohibited', 'stop', 'clear'],
  Clipboard: ['clipboard', 'copy', 'paste', 'notes', 'document'],
  Clock: ['core', 'date', 'hands', 'hour', 'time', 'timer'],
  Clone: ['copy', 'duplicate', 'layers', 'clone'],
  Close: ['cancel', 'core', 'delete', 'escape', 'exit', 'remove'],
  ClosedCaption: ['accessibility', 'closed'],
  Cloud: ['computing', 'data', 'network', 'storage', 'weather', 'cloud'],
  CloudAdd: ['cloud', 'storage', 'add', 'upload', 'plus'],
  CloudComputer: ['computing', 'data', 'network', 'storage', 'cloud', 'online'],
  CloudDownload: ['arrows', 'computing', 'data', 'network', 'storage', 'cloud'],
  CloudLocked: ['cloud', 'storage', 'lock', 'secure', 'restricted'],
  CloudOffline: ['cloud', 'storage', 'offline', 'disconnected', 'unavailable'],
  CloudSoftware: [
    'application',
    'computing',
    'data',
    'network',
    'storage',
    'cloud',
  ],
  CloudUpload: ['arrows', 'backup', 'computing', 'data', 'hosting', 'network'],
  Cluster: ['interconnect', 'map', 'network', 'cluster'],
  CoatCheck: ['clothes', 'hanger', 'hotel', 'coat'],
  Code: ['application', 'coding', 'development', 'programming', 'web', 'code'],
  Coffee: ['bean', 'caffeine', 'goodstuff', 'java', 'coffee'],
  Columns: ['chart', 'graph', 'layout', 'table', 'columns'],
  Command: ['cli', 'line', 'console', 'code', 'command'],
  Compare: ['ab', 'a/b', 'analytics', 'balance', 'testing', 'variations'],
  Compass: ['direction', 'location', 'map', 'navigation', 'tools', 'compass'],
  Compliance: ['checklist', 'clipboard', 'mark', 'protection', 'compliance'],
  Configure: ['core', 'preferences', 'setting', 'settings', 'tools', 'wrench'],
  Connectivity: ['network', 'plug', 'connectivity', 'connection'],
  Console: ['core', 'debug', 'log', 'console'],
  Contact: ['avatar', 'icommunication', 'phone', 'profile', 'contact'],
  Contract: ['arrows', 'exit fullscreen', 'minimize', 'contract'],
  Copy: ['documents', 'duplicate', 'files', 'paste', 'copy'],
  Cpu: ['technology', 'processor', 'unit', 'cpu'],
  CreditCard: ['amex', 'atm', 'debit', 'mastercard', 'visa', 'wallet'],
  Cube: ['3d', 'box', 'container', 'database', 'package', 'cube'],
  Cubes: ['3d', 'box', 'container', 'database', 'package', 'cubes'],
  Currency: ['cash', 'dollar', 'finance', 'payment', 'money', 'currency'],
  Cursor: ['arrows', 'click', 'mouse', 'pointer', 'cursor'],
  Cut: ['scissors', 'tools', 'cut', 'trim'],
  Cycle: ['arrows', 'recycle', 'refresh', 'repeat', 'cycle'],
  Dashboard: ['dashboard', 'panel', 'overview', 'analytics', 'control'],
  Database: ['rack', 'server', 'storage', 'database'],
  Deliver: ['delivery', 'shipping', 'transportation', 'truck', 'deliver'],
  Deploy: ['rocket', 'spaceship', 'deploy'],
  Descend: ['arrows', 'downward', 'sort', 'descend'],
  Descending: ['arrows', 'down', 'downward', 'sort', 'descending'],
  Desktop: ['computer', 'display', 'monitor', 'pc', 'screen', 'desktop'],
  Detach: ['cut', 'paperclip', 'remove', 'detach'],
  Device: ['iot', 'technology', 'tv', 'device'],
  Dial: ['audio', 'sound', 'speaker', 'dial'],
  Diamond: ['gem', 'jewelry', 'stone', 'diamond'],
  Directions: ['arrows', 'location', 'navigation', 'directions'],
  DisabledOutline: [
    'checkbox',
    'indeterminate',
    'disabled',
    'inactive',
    'outline',
  ],
  Disc: ['disc', 'cd', 'dvd', 'media', 'music', 'audio'],
  Dislike: ['thumbs', 'down', 'like', 'dislike'],
  DislikeFill: ['thumbs', 'down', 'like', 'dislike', 'filled', 'solid'],
  Document: ['document', 'file', 'record'],
  DocumentCloud: ['cloud', 'files', 'folder', 'page', 'paper', 'document'],
  DocumentConfig: ['files', 'folder', 'gear', 'page', 'paper', 'document'],
  DocumentCsv: ['extension', 'files', 'format', 'folder', 'page', 'paper'],
  DocumentDownload: ['arrows', 'files', 'import', 'get', 'page', 'paper'],
  DocumentExcel: [
    'extension',
    'files',
    'format',
    'folder',
    'microsoft',
    'office',
  ],
  DocumentImage: ['files', 'folder', 'page', 'paper', 'photography', 'photos'],
  DocumentLocked: ['files', 'folder', 'page', 'paper', 'password', 'secure'],
  DocumentMissing: ['delete', 'error', 'files', 'folder', 'page', 'paper'],
  DocumentNotes: ['extension', 'files', 'folder', 'page', 'paper', 'document'],
  DocumentOutlook: [
    'extension',
    'files',
    'folder',
    'microsoft',
    'office',
    'page',
  ],
  DocumentPdf: ['extension', 'files', 'folder', 'format', 'page', 'paper'],
  DocumentPerformance: ['arrows', 'files', 'folder', 'format', 'page', 'paper'],
  DocumentPpt: ['extension', 'files', 'folder', 'microsoft', 'office', 'page'],
  DocumentRtf: ['extension', 'files', 'folder', 'format', 'page', 'paper'],
  DocumentSound: ['audio', 'files', 'folder', 'music', 'page', 'paper'],
  DocumentStore: ['data', 'files', 'folder', 'page', 'paper', 'document'],
  DocumentTest: ['biology', 'chemistry', 'files', 'flask', 'folder', 'page'],
  DocumentText: ['extension', 'files', 'folder', 'format', 'page', 'paper'],
  DocumentThreat: ['bomb', 'danger', 'files', 'folder', 'malware', 'page'],
  DocumentTime: ['alarm', 'clock', 'event', 'files', 'folder', 'hands'],
  DocumentTransfer: ['arrows', 'files', 'folder', 'page', 'paper', 'document'],
  DocumentTxt: ['extension', 'files', 'folder', 'format', 'page', 'paper'],
  DocumentUpdate: ['arrows', 'files', 'folder', 'page', 'paper', 'refresh'],
  DocumentUpload: ['arrows', 'files', 'import', 'get', 'page', 'paper'],
  DocumentUser: ['account', 'avatar', 'files', 'folder', 'page', 'paper'],
  DocumentVerified: ['check', 'files', 'folder', 'mark', 'page', 'paper'],
  DocumentVideo: ['camera', 'files', 'folder', 'page', 'paper', 'video'],
  DocumentWarning: ['document', 'file', 'record'],
  DocumentWindows: [
    'executable',
    'extension',
    'files',
    'folder',
    'page',
    'paper',
  ],
  DocumentWord: ['extension', 'files', 'folder', 'microsoft', 'office', 'page'],
  DocumentZip: ['compressed', 'extension', 'files', 'folder', 'format', 'page'],
  Domain: ['internet', 'website', 'www', 'domain'],
  Down: ['arrows', 'expand', 'direction', 'drop', 'down', 'arrow'],
  Download: ['arrows', 'cloud', 'core', 'import', 'get', 'navigation'],
  Drag: ['drop', 'drag'],
  DriveCage: ['data', 'disk', 'rack', 'storage', 'drive'],
  Duplicate: ['add', 'copy', 'duplicate', 'clone'],
  Edit: ['change', 'core', 'draw', 'modify', 'pen', 'pencil'],
  Eject: ['media', 'player', 'eject', 'remove'],
  Element: ['HPE', 'element', 'brand'],
  Elevator: ['down', 'lift', 'up', 'transportation', 'elevator'],
  Emergency: ['emergency', 'alert', 'critical'],
  EmergencyFill: ['emergency', 'alert', 'critical'],
  Erase: ['delete', 'eraser', 'remove', 'erase'],
  Escalator: [
    'stairs',
    'staircase',
    'moving',
    'transportation',
    'person',
    'up',
  ],
  Expand: ['arrows', 'direction', 'maximize', 'full', 'screen', 'expand'],
  Fan: ['air', 'cooling', 'ventilator', 'fan'],
  FastForward: ['arrows', 'next', 'player', 'right', 'fast'],
  Favorite: ['heart', 'like', 'favorite'],
  Filter: ['core', 'funnel', 'refine', 'sort', 'triage', 'filter'],
  FingerPrint: ['security', 'biometric', 'scan', 'finger', 'print', 'printer'],
  Firewall: ['cyber', 'protect', 'web', 'firewall'],
  FiveG: ['5g', 'network', 'mobile', 'signal', 'connectivity', 'wireless'],
  Flag: ['core', 'nation', 'warn', 'warning', 'flag'],
  Flows: ['flows', 'grouping', 'connection', 'process', 'diagram'],
  Focus: ['focus', 'target', 'highlight'],
  Folder: ['documents', 'data', 'files', 'folder', 'directory', 'collection'],
  FolderAdd: ['folder', 'directory', 'collection', 'add', 'new', 'plus'],
  FolderCycle: ['documents', 'data', 'files', 'recycle', 'refresh', 'folder'],
  FolderOpen: [
    'documents',
    'data',
    'files',
    'folder',
    'directory',
    'collection',
  ],
  FolderSearch: [
    'folder',
    'directory',
    'collection',
    'search',
    'find',
    'magnifier',
  ],
  ForwardTen: ['arrows', 'seconds', 'player', 'skip', 'forward'],
  Gallery: ['image', 'pictures', 'photography', 'photos', 'gallery'],
  Gamepad: ['joystick', 'play', 'sports', 'gamepad'],
  Gateway: ['network', 'technology', 'gateway', 'access'],
  Gem: ['miscellaneous', 'shape', 'gem', 'diamond', 'jewel'],
  Gift: ['birthday', 'box', 'christmas', 'present', 'gift'],
  Globe: ['earth', 'global', 'internet', 'planet', 'world', 'globe'],
  Gpu: ['gpu', 'graphics', 'card', 'hardware', 'processing', 'compute'],
  Grid: ['line', 'layout', 'grid', 'tiles'],
  Group: ['people', 'team', 'person', 'users', 'group'],
  Grow: ['growth', 'plant', 'grow', 'increase', 'expand'],
  Halt: ['hand', 'sign', 'stop', 'halt'],
  Help: ['faq', 'help', 'support'],
  HelpBook: [
    'Help documentation',
    'reserve usage for contextual help',
    'wiki',
    'documentation.',
    'help',
  ],
  Hide: ['eye', 'form', 'close', 'hide'],
  History: ['backup', 'clock', 'hands', 'timer', 'schedule', 'history'],
  Home: ['building', 'estate', 'house', 'real', 'home', 'start'],
  Host: ['computer', 'database', 'hosting', 'mainframe', 'rack', 'server'],
  HostMaintenance: [
    'hosting',
    'rack',
    'server',
    'service',
    'settings',
    'repair',
  ],
  IceCream: ['dessert', 'food', 'ice cream', 'treat'],
  Image: ['photography', 'photos', 'picture', 'image'],
  Impact: ['crash', 'explode', 'impact', 'effect', 'result'],
  InProgress: ['clock', 'hourglass', 'timer', 'in', 'progress', 'loading'],
  Inbox: ['email', 'messages', 'letter', 'tray', 'inbox'],
  Info: ['document', 'faq', 'help', 'hint', 'info'],
  Inherit: ['family', 'pedigree', 'tree', 'inherit'],
  Insecure: ['insecure', 'untrusted', 'warning', 'risk', 'unsafe'],
  Inspect: ['eye', 'glasses', 'spectacles', 'inspect'],
  Install: ['configuration', 'download', 'settings', 'setup', 'install'],
  Integration: ['connection', 'plug', 'system', 'integration'],
  Iteration: ['cascade', 'iterate', 'repeat', 'stack', 'steps', 'iteration'],
  Key: ['key', 'lock', 'access', 'security'],
  Keyboard: ['accessibility', 'tab', 'technology', 'keyboard'],
  Language: ['earth', 'internet', 'translate', 'world', 'language'],
  Layer: ['arrange', 'cascade', 'layers', 'stack', 'layer'],
  Left: ['arrows', 'back', 'backward', 'core', 'direction', 'left'],
  Like: ['favorite', 'heart', 'thumbs', 'up', 'like'],
  LikeFill: ['favorite', 'heart', 'thumbs', 'up', 'like', 'filled'],
  Link: ['chain', 'connection', 'network', 'web', 'link', 'url'],
  LinkBottom: [
    'navigation',
    'links',
    'anchors',
    'pagination',
    'scroll',
    'direction',
    'down',
    'bottom',
  ],
  LinkNext: [
    'navigation',
    'links',
    'anchors',
    'pagination',
    'scroll',
    'direction',
    'forward',
    'next',
  ],
  LinkPrev: [
    'navigation',
    'links',
    'anchors',
    'pagination',
    'scroll',
    'direction',
    'backward',
    'back',
  ],
  LinkTop: [
    'navigation',
    'links',
    'anchors',
    'pagination',
    'scroll',
    'direction',
    'up',
    'top',
  ],
  List: ['hamburger', 'navigation', 'options', 'orderedlist', 'list'],
  ListOrdered: ['ist', 'ordered', 'numbered', 'sequence', 'items', 'ol'],
  ListUnordered: ['list', 'unordered', 'bullets', 'items', 'simple', 'ul'],
  Local: ['flag', 'language', 'location', 'usa', 'local'],
  Location: ['gps', 'map', 'navigation', 'pin', 'location'],
  LocationPin: ['gps', 'map', 'navigation', 'pin', 'location'],
  Lock: ['close', 'key', 'password', 'protectio', 'secure', 'security'],
  Lodging: ['lodging', 'hotel', 'accommodation', 'stay', 'travel'],
  Login: ['login', 'sign in', 'access', 'authentication', 'account'],
  Logout: ['logout', 'sign out', 'exit', 'leave', 'end'],
  Lounge: ['chair', 'furniture', 'sofa', 'lounge'],
  Magic: ['magic', 'wand', 'sparkle', 'tool', 'effect'],
  Mail: ['mail', 'email', 'message', 'inbox', 'letter', 'envelope'],
  Manual: ['stick', 'joystick', 'manual', 'guide', 'instructions'],
  Map: ['map', 'location', 'navigation'],
  MapAdd: ['map', 'location', 'navigation', 'add', 'new', 'plus'],
  Meeting: ['meeting', 'group', 'people', 'discussion', 'collaboration'],
  Memory: ['technology', 'computer', 'memory', 'ram', 'hardware'],
  Menu: ['hamburger', 'list', 'navigation', 'options', 'menu'],
  Microphone: ['audio', 'mic', 'music', 'sound', 'microphone'],
  Mode: ['mode', 'display', 'dark', 'light', 'toggle'],
  Money: ['cash', 'coins', 'currency', 'dollar', 'finance', 'money'],
  Monitor: ['computer', 'crt', 'desktop', 'display', 'screen', 'monitor'],
  Moon: ['dark', 'nature', 'moon', 'night'],
  More: ['actions', 'core', 'ellipses', 'more'],
  MoreVertical: ['actions', 'core', 'ellipses', 'more', 'vertical', 'upright'],
  Mouse: ['hardware', 'technology', 'mouse'],
  Multimedia: ['clapboard', 'cinema', 'film', 'video', 'movie', 'multimedia'],
  Multiple: ['cascade', 'repeat', 'stack', 'steps', 'multiple'],
  Music: ['audio', 'notes', 'sound', 'play', 'music'],
  Navigate: ['guide', 'road', 'sign', 'street', 'way', 'navigate'],
  Network: ['media', 'connection', 'divergence', 'fork', 'branch', 'network'],
  NetworkDrive: [
    'media',
    'connection',
    'divergence',
    'fork',
    'branch',
    'technology',
  ],
  NetworkSwitch: ['dos', 'line', 'command', 'console', 'network'],
  New: ['asterisk', 'add', 'create', 'plus', 'new'],
  NewWindow: ['new window', 'external', 'open', 'link', 'browser'],
  Nodes: ['connection', 'network', 'nodes', 'graph'],
  Note: ['document', 'file', 'paper', 'note', 'music', 'sound'],
  Notes: ['document', 'file', 'paper', 'notes'],
  Notification: ['alarm', 'alert', 'bell', 'core', 'messages', 'notify'],
  ObjectGroup: ['group', 'objects', 'combine'],
  ObjectUngroup: ['ungroup', 'objects', 'separate'],
  OfflineStorage: ['backup', 'tape', 'offline', 'storage', 'disk'],
  Optimize: ['analytics', 'chart', 'growth', 'optimize'],
  Organization: ['building', 'organization'],
  Overview: ['binoculars', 'overview', 'summary', 'dashboard'],
  Package: ['controls', 'box', 'package', 'shipping'],
  Paint: ['bucket', 'color', 'paint', 'fill'],
  Pan: ['arrows', 'drag', 'move', 'pan'],
  Pause: ['player', 'pause', 'hold', 'media', 'audio', 'video'],
  PauseFill: ['player', 'pause', 'hold', 'media', 'filled', 'solid'],
  Performance: ['optimization', 'performance', 'speed', 'metrics'],
  PersonalComputer: ['pc', 'monitor', 'screen', 'personal'],
  Phone: ['call', 'chat', 'conference', 'media', 'mobile', 'phone'],
  PhoneFlip: ['call', 'chat', 'conference', 'flip', 'media', 'mobile'],
  PhoneHorizontal: ['call', 'chat', 'conference', 'media', 'mobile', 'phone'],
  PhoneVertical: ['call', 'chat', 'conference', 'media', 'mobile', 'phone'],
  Pin: ['gps', 'location', 'map', 'navigation', 'pin', 'tack'],
  Play: ['media', 'music', 'player', 'video', 'play', 'start'],
  PlayFill: ['media', 'music', 'player', 'video', 'play', 'start'],
  Power: ['off', 'switch', 'power', 'on'],
  PowerCycle: ['power', 'cycle', 'reboot', 'on', 'off'],
  PowerForceShutdown: ['power', 'off', 'shut down', 'on'],
  PowerReset: ['power', 'reset', 'reboot', 'on', 'off'],
  Print: ['laser', 'printer', 'print', 'document'],
  Progress: ['bar', 'progress', 'loading', 'status'],
  Projects: ['Project', 'squares', 'tasks', 'projects'],
  Qr: ['qr code', 'scan', 'barcode'],
  Redo: ['redo', 'repeat', 'forward'],
  Refresh: ['arrows', 'backup', 'core', 'reload', 'repeat', 'pull'],
  Resources: ['cascade', 'layers', 'multiple', 'stack', 'resources'],
  Restaurant: ['chef', 'cook', 'food', 'hat', 'restaurant'],
  Restroom: ['restroom', 'bathroom', 'toilet', 'wc'],
  RestroomMen: ['restroom', 'man', 'mens', 'bathroom', 'toilet', 'wc'],
  RestroomUnisex: ['restroom', 'unisex', 'bathroom', 'toilet', 'wc'],
  RestroomWomen: ['restroom', 'women', 'womens', 'bathroom', 'toilet', 'wc'],
  Resume: ['resume', 'play', 'player', 'continue', 'media', 'start'],
  Return: ['return', 'enter', 'keyboard', 'key', 'carriage'],
  Revert: ['arrows', 'history', 'undo', 'revert'],
  Rewind: ['back', 'media', 'player', 'rewind'],
  Right: ['arrows', 'core', 'direction', 'forward', 'next', 'right'],
  Risk: ['casino', 'dice', 'game', 'gaming', 'probability', 'risk'],
  Robot: ['android', 'automatic', 'automation', 'career', 'job', 'layoff'],
  RotateLeft: ['rotate', 'arrow', 'left', 'previous', 'back', 'direction'],
  RotateRight: ['rotate', 'arrow', 'right', 'next', 'forward', 'direction'],
  Rss: ['feed', 'news', 'signal', 'syndication', 'rss'],
  Run: ['exit', 'evacuation', 'fire', 'lead', 'person', 'sport'],
  Sans: ['technology', 'type', 'sans', 'typography', 'font'],
  Satellite: ['antenna', 'communication', 'dish', 'space', 'satellite'],
  Save: ['arrows', 'floppy', 'store', 'storage', 'save'],
  Scan: ['document', 'scanner', 'scan', 'barcode', 'reader'],
  Scorecard: ['clipboard', 'game', 'mark', 'scorecard'],
  Script: ['miscellaneous', 'script'],
  SD: ['hardware', 'card', 'technology', 'sd'],
  Search: ['core', 'find', 'lookup', 'magnifier', 'zoom', 'search'],
  SearchAdvanced: ['search', 'find', 'magnifier'],
  Secure: ['closed', 'locked', 'protected', 'security', 'ssl', 'secure'],
  Select: ['cursor', 'pointer', 'selection', 'select'],
  Selection: ['selection', 'choose', 'pick', 'highlight', 'cursor'],
  Semantics: ['semantics', 'meaning', 'language', 'structure', 'logic'],
  Send: ['airplane', 'email', 'messages', 'paper', 'send'],
  Sensor: ['sensor', 'detect', 'device', 'input', 'hardware'],
  SensorLocked: ['sensor', 'detect', 'locked', 'restricted', 'secure'],
  SensorOff: ['sensor', 'detect', 'off', 'disabled', 'inactive'],
  Server: ['computer', 'hosting', 'mainframe', 'servers', 'server'],
  ServerCluster: [
    'cluster',
    'computer',
    'hosting',
    'mainframe',
    'servers',
    'server',
  ],
  Servers: ['cluster', 'computer', 'hosting', 'mainframe', 'servers'],
  ServicePlay: ['service', 'play', 'start', 'media', 'audio', 'video'],
  Services: ['action', 'cloud', 'gears', 'services'],
  Settings: ['configure', 'gear', 'settings', 'preferences', 'config'],
  Share: ['connections', 'export', 'sharing', 'open', 'network', 'publish'],
  Shield: ['antivirus', 'secure', 'security', 'shield'],
  ShieldCheck: ['shield', 'secure', 'verified'],
  ShieldEmergency: ['shield', 'emergency', 'alert'],
  ShieldSecurity: ['shield', 'security', 'protection'],
  ShieldUnsecure: ['shield', 'insecure', 'warning'],
  Shift: ['divide', 'partition', 'separate', 'split', 'shift'],
  Shop: ['buy', 'cart', 'checkout', 'bag', 'shopping', 'shop'],
  Sidebar: ['columns', 'layout', 'navigation', 'right', 'sidebar'],
  Sign: ['devil', 'hand', 'heavy', 'horns', 'metal', 'rock'],
  Spa: ['lotus', 'plant', 'flower', 'yoga', 'spa'],
  Split: ['columns', 'layout', 'navigation', 'split'],
  Splits: ['columns', 'layout', 'navigation', 'splits'],
  Stakeholder: ['business', 'person', 'stakeholder'],
  Star: ['badge', 'rating', 'star'],
  StarFill: ['badge', 'rating', 'star', 'filled', 'solid'],
  StarHalf: ['badge', 'rating', 'star'],
  StarHalfFill: ['badge', 'rating', 'star', 'filled', 'solid'],
  StatusCritical: ['error', 'halt', 'stop', 'warning', 'critical', 'status'],
  StatusCriticalSystem: ['status', 'critical', 'state', 'indicator'],
  StatusDisabled: ['faq', 'help', 'hint', 'information', 'info', 'status'],
  StatusDisabledSystem: [
    'faq',
    'help',
    'hint',
    'information',
    'info',
    'status',
  ],
  StatusGood: ['accept', 'check', 'ok', 'status', 'state', 'indicator'],
  StatusGoodSystem: ['status', 'ok', 'normal', 'state', 'indicator'],
  StatusInfo: ['faq', 'help', 'hint', 'information', 'info', 'status'],
  StatusInfoSystem: ['faq', 'help', 'hint', 'information', 'info', 'status'],
  StatusUnknown: [
    'hint',
    'information',
    'service',
    'support',
    'question',
    'status',
  ],
  StatusUnknownSystem: ['status', 'unknown', 'state', 'indicator'],
  StatusWarning: ['warning', 'exclamation', 'status', 'state', 'indicator'],
  StatusWarningSystem: ['status', 'warning', 'state', 'indicator'],
  Steps: ['steps', 'sequence', 'process'],
  Stop: ['halt', 'player', 'stop', 'end', 'media', 'audio'],
  StopFill: ['halt', 'player', 'stop', 'end', 'media', 'filled'],
  Storage: ['archives', 'drawers', 'storage'],
  StreetView: ['location', 'map', 'person', 'street'],
  Subtract: ['core', 'decrement', 'minus', 'reduce', 'remove', 'subtraction'],
  Sun: ['light', 'nature', 'sun', 'day'],
  Support: ['help', 'life', 'lifesaver', 'preserver', 'safety', 'support'],
  Swim: ['person', 'sport', 'swimmer', 'swimming', 'swim'],
  Switch: ['hardware', 'network', 'technology', 'switch'],
  Sync: ['refresh', 'reload', 'update', 'sync'],
  System: ['computer', 'configuration', 'gear', 'settings', 'system'],
  Table: ['spreadsheet', 'table', 'grid', 'data'],
  TableAdd: ['new', 'plus', 'spreadsheet', 'table', 'grid', 'data'],
  TableAddColumn: ['table', 'add column', 'insert'],
  TableSearch: ['table', 'grid', 'data', 'search', 'find', 'magnifier'],
  Tag: ['label', 'retail', 'ticket', 'travel', 'tag'],
  Tape: ['archive', 'backup', 'storage', 'tape'],
  Target: ['bulleye', 'darts', 'goal', 'target'],
  Task: ['details', 'done', 'list', 'survey', 'task'],
  Technology: ['circuit', 'device', 'electronics', 'technology'],
  Temperature: ['temperature', 'heat', 'cold', 'weather', 'degree'],
  Template: ['application', 'columns', 'layout', 'navigation', 'template'],
  Test: [
    'biology',
    'chemistry',
    'experiment',
    'flask',
    'healthcare',
    'laboratory',
  ],
  TestDesktop: [
    'biology',
    'chemistry',
    'experiment',
    'laboratory',
    'prototype',
    'research',
  ],
  TextWrap: [
    'around',
    'text wrap',
    'wrap',
    'paragraph',
    'line break',
    'layout',
  ],
  Theme: ['theme', 'style', 'appearance', 'layout', 'design'],
  Threats: ['bomb', 'danger', 'explosive', 'security', 'threats'],
  ThreeD: ['3d', 'cube', 'box', 'rotation', 'three'],
  ThreeDEffects: ['3d', 'effects', 'render'],
  Ticket: ['cinema', 'concert', 'movie', 'travel', 'ticket'],
  Time: ['chart', 'line', 'data', 'time'],
  Tip: ['bubble', 'chat', 'messages', 'tooltip', 'tip'],
  Tools: ['hammer', 'mallet', 'tools', 'tool'],
  Tooltip: ['bubble', 'chat', 'elipses', 'messages', 'tooltip'],
  Train: ['railroad', 'subway', 'transportation', 'travel', 'train'],
  Transaction: ['activity', 'arrows', 'transaction'],
  Trash: ['bin', 'clear', 'core', 'delete', 'eliminate', 'garbage'],
  Tree: ['branch', 'forest', 'plant', 'tree'],
  TreeNode: ['branch', 'flow', 'organizstion', 'view', 'tree'],
  Trigger: ['bolt', 'electricity', 'lightning', 'power', 'quick', 'storm'],
  Trophy: ['award', 'cup', 'medal', 'prize', 'trophy', 'winner'],
  Tty: ['accessibility', 'teletype', 'teleprinter', 'tdd', 'tty'],
  Undo: ['undo', 'back', 'reverse'],
  Unlink: ['break', 'chain', 'disconnect', 'unlink'],
  Unlock: ['open', 'key', 'password', 'protection', 'secure', 'security'],
  Unsorted: ['arrows', 'up', 'down', 'sort', 'sortable', 'unsorted'],
  Up: ['arrows', 'collapse', 'direction', 'up', 'arrow', 'navigation'],
  Update: ['arrows', 'change', 'core', 'reload', 'refresh', 'update'],
  Upgrade: ['arrows', 'circle', 'upgrade'],
  Upload: ['arrows', 'attach', 'attachment', 'cloud', 'core', 'export'],
  UsbKey: ['hardware', 'memory', 'technology', 'usb', 'key', 'access'],
  User: ['account', 'avatar', 'core', 'person', 'profile', 'male'],
  UserAdd: ['add', 'account', 'avatar', 'new', 'person', 'profile'],
  UserAdmin: ['account', 'avatar', 'person', 'profile', 'security', 'key'],
  UserExpert: ['account', 'admin', 'avatar', 'check', 'person', 'profile'],
  UserFemale: ['account', 'avatar', 'core', 'person', 'profile', 'woman'],
  UserManager: ['account', 'avatar', 'boss', 'person', 'profile', 'user'],
  UserNew: ['add', 'account', 'avatar', 'new', 'person', 'profile'],
  UserPolice: ['account', 'avatar', 'marshal', 'officer', 'person', 'profile'],
  UserSettings: ['account', 'avatar', 'gear', 'person', 'profile', 'settings'],
  UserWorker: [
    'account',
    'avatar',
    'construction',
    'hardhat',
    'helmut',
    'person',
  ],
  Validate: ['accept', 'approve', 'ok', 'success', 'validate'],
  Vend: ['automated', 'dispensing', 'snacks', 'vending', 'vend'],
  Video: ['camera', 'movie', 'video', 'media', 'audio', 'player'],
  View: ['eye', 'open', 'visibility', 'view'],
  VirtualMachine: ['vmware', 'virtual'],
  VirtualStorage: ['storage', 'virtual', 'cloud', 'circles', 'stack'],
  VMMaintenance: ['tools', 'vmware', 'wrench', 'vm'],
  Volume: ['audio', 'sound', 'speaker', 'volume', 'media', 'video'],
  VolumeLow: ['audio', 'sound', 'speaker', 'volume', 'media', 'video'],
  VolumeMute: ['audio', 'mute', 'sound', 'speaker', 'volume', 'media'],
  Vulnerability: [
    'aim',
    'crosshairs',
    'hunting',
    'security',
    'target',
    'vulnerability',
  ],
  Waypoint: ['arrows', 'cursor', 'compass', 'gps', 'location', 'navigation'],
  Webcam: ['image', 'lens', 'photos', 'photography', 'picture', 'shot'],
  Wheelchair: [
    'accessibility',
    'disabled',
    'disability',
    'handicap',
    'person',
    'wheelchair',
  ],
  WheelchairActive: [
    'accessibility',
    'disabled',
    'disability',
    'handicap',
    'person',
    'wheelchair',
  ],
  Wifi: ['network', 'connection', 'signal', 'wifi', 'wireless'],
  WifiLocked: ['wifi', 'wireless', 'lock', 'secure', 'restricted'],
  WifiLow: ['network', 'connection', 'weak', 'signal', 'wifi', 'wireless'],
  WifiMedium: ['network', 'connection', 'medium', 'signal', 'wifi', 'wireless'],
  WifiNone: ['network', 'connection', 'signal', 'wifi', 'wireless'],
  WifiOff: ['wifi', 'wireless', 'off', 'disabled', 'disconnected'],
  Workshop: ['business', 'conference', 'speaker', 'workshop'],
  Yoga: ['asana', 'person', 'sport', 'yoga'],
  ZoomIn: ['in', 'plus', 'magnify', 'zoom'],
  ZoomOut: ['out', 'minus', 'magnify', 'zoom'],
};
