import { Data, DataTable, Pagination, Box, Text } from 'grommet';

const columns = [
  {
    property: 'serialNumber',
    header: 'Serial number',
    primary: true,
  },
  {
    property: 'name',
    header: 'Name',
    render: datum => (datum.name ? datum.name : '--'),
  },
  {
    property: 'type',
    header: 'Type',
  },
  {
    property: 'make',
    header: 'Make',
  },
  {
    property: 'country',
    header: 'Country',
  },
  {
    property: 'state',
    header: 'State',
  },
  {
    property: 'city',
    header: 'City',
    render: datum => <Text truncate="tip">{datum.city}</Text>,
  },
  {
    property: 'model',
    header: 'Model',
    render: datum => <Text truncate="tip">{datum.model}</Text>,
  },
  {
    property: 'totalEnergy',
    header: 'Total energy',
    units: 'kWh',
  },
];

const data = [
  {
    serialNumber: 'fg4agao01r8x5oz7f',
    city: 'Palo Alto',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_0',
  },
  {
    serialNumber: 'ljyyfpc02tlgpnls3',
    city: 'Palo Alto',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo001ruh3s74q',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc0p6rnexjs',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc0tj092j29',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao0omfitumg',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_5',
  },
  {
    serialNumber: 'fg4agao02cf6arety',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_6_test',
  },
  {
    serialNumber: 'fg4agao01qe4macw7',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc01u9d5etcr',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo029fhmklcq',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'MyDevice_local',
  },
  {
    serialNumber: 'jqspeyo015yq2h50b',
    city: 'Palo Alto',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_10',
  },
  {
    serialNumber: 'fg4agao02h8juiosf',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc033l0fal80',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_12_test',
  },
  {
    serialNumber: 'ljyyfpc02vu079llx',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo0023apx8ykf',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao01pjdri61w',
    city: 'New York',
    state: 'California',
    region: 'US East',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_15',
  },
  {
    serialNumber: 'fg4agao02ukw569p7',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc01i5bhy9y5',
    city: 'New York',
    state: 'California',
    region: 'US East',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc01mt2kkowg',
    city: 'Palo Alto',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_18_test',
  },
  {
    serialNumber: 'ljyyfpc032xr7fiym',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo002su2qh7sl',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_20',
  },
  {
    serialNumber: 'fg4agao0y7vnahc7',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc01mio3vvlt',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo023eg0dnfk',
    city: 'Palo Alto',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo021i8p7av3',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_24_test',
  },
  {
    serialNumber: 'fg4agao02lap1wyfx',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
    name: 'PROD_25',
  },
  {
    serialNumber: 'fg4agao0rr0qp5mx',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo025r11dy47',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao01156u2fa6',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo02gixjl6nc',
    city: 'New York',
    state: 'California',
    region: 'US East',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc0kbp821tq',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
    name: 'PROD_30',
  },
  {
    serialNumber: 'jqspeyo018zcwokes',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc019xfmtlfr',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo02t1pwq4vf',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc01gywd6vm3',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo0030wd5x8bk',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_35',
  },
  {
    serialNumber: 'jqspeyo03cxzw9hqh',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
    name: 'DEV_36_test',
  },
  {
    serialNumber: 'erwnuo00380sakjtz',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo001pag2g80t',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc0183l9a89y',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc013txgh3yu',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_40',
  },
  {
    serialNumber: 'jqspeyo02tzq272eq',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc0ls7nphbc',
    city: 'New York',
    state: 'California',
    region: 'US East',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_42_test',
  },
  {
    serialNumber: 'ljyyfpc016sn9e733',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc0s4yypjjx',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo001b4hj6edg',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_45',
  },
  {
    serialNumber: 'dwjtzpc0yha23okg',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc026d6z6jmp',
    city: 'New York',
    state: 'California',
    region: 'US East',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao02rr8catp5',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_48_test',
  },
  {
    serialNumber: 'fg4agao01m2fvyepf',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao01bq8g5pjj',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
    name: 'PROD_50',
  },
  {
    serialNumber: 'ljyyfpc0hil3mp1g',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo001sakqrpnl',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo0t29p4pmw',
    city: 'New York',
    state: 'California',
    region: 'US East',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao01oarlitf6',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_54_test',
  },
  {
    serialNumber: 'dwjtzpc025oj5og46',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
    name: 'PROD_55',
  },
  {
    serialNumber: 'erwnuo0015zh8wsn2',
    city: 'Palo Alto',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo0ggy6ftaa',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao03bum8d73v',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc02iyugxsng',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo0y4o1i77z',
    city: 'Palo Alto',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_60',
  },
  {
    serialNumber: 'fg4agao0hom4bsld',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo02e2g8b57u',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo002rqunlm04',
    city: 'New York',
    state: 'California',
    region: 'US East',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao02oo43m2rs',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc0184dj81o9',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_65',
  },
  {
    serialNumber: 'jqspeyo03e59w0n26',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_66_test',
  },
  {
    serialNumber: 'dwjtzpc0160ov31si',
    city: 'Palo Alto',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo002sarjhtwd',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo034nct3btw',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc028sof6g7s',
    city: 'New York',
    state: 'California',
    region: 'US East',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_70',
  },
  {
    serialNumber: 'erwnuo002rvtqkase',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo001ngq5jhe0',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_72_test',
  },
  {
    serialNumber: 'dwjtzpc01sd1jajyn',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao01cvf0dy4q',
    city: 'Palo Alto',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo01ald75it1',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
    name: 'PROD_75',
  },
  {
    serialNumber: 'jqspeyo01kizuiud6',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc0ufdrh7lh',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc01pw6tsuzr',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_78_test',
  },
  {
    serialNumber: 'fg4agao02o9gnvte6',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo001totx0ppy',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
    name: 'PROD_80',
  },
  {
    serialNumber: 'jqspeyo021dpm7pb9',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc01v73ey0s2',
    city: 'New York',
    state: 'California',
    region: 'US East',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc0v4elga55',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'HPE Alletra Storage MP',
    type: 'Storage',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'jqspeyo02zmshl9vo',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_84_test',
  },
  {
    serialNumber: 'erwnuo00vep4luyx',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_85',
  },
  {
    serialNumber: 'ljyyfpc01dd9951lj',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc01v6j56193',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao02p7ygk01r',
    city: 'San Jose',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo001ph5mczzq',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc0yptxqdup',
    city: 'Mountain View',
    state: 'California',
    region: 'US West',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'PROD_90',
  },
  {
    serialNumber: 'jqspeyo01v7t08u86',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'HPE Synergy 12000 w/ 3x Synergy 480 Gen 10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'dwjtzpc02j948b3k7',
    city: 'Houston',
    state: 'California',
    region: 'US Central',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao0nasbwzph',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'erwnuo001avl6i8mq',
    city: 'Palo Alto',
    state: 'California',
    region: 'US West',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'ljyyfpc01qozicw35',
    city: 'Fort Collins',
    state: 'California',
    region: 'US Mountain',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
    name: 'PROD_95',
  },
  {
    serialNumber: 'jqspeyo031tez0vfi',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
    name: 'DEV_96_test',
  },
  {
    serialNumber: 'fg4agao02r2t60f2m',
    city: 'Los Angeles',
    state: 'California',
    region: 'US West',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao02m711ifle',
    city: 'New York',
    state: 'California',
    region: 'US East',
    model: 'UCS C220 M6 Rack Server',
    type: 'Compute',
    make: 'Dell',
    country: 'USA',
  },
  {
    serialNumber: 'fg4agao01h70sl67k',
    city: 'Austin',
    state: 'California',
    region: 'US Central',
    model: 'HPE ProLiant D 380 Gen10',
    type: 'Compute',
    make: 'HPE',
    country: 'USA',
  },
];

export const Devices = () => {
  return (
    <Data data={data} toolbar>
      <Box overflow={{ horizontal: 'auto' }}>
        <DataTable
          alignSelf="start"
          columns={columns}
          sortable
          verticalAlign={{ body: 'top' }}
        />
      </Box>
      <Box border="top" pad={{ vertical: 'xsmall' }}>
        <Pagination alignSelf="end" />
      </Box>
    </Data>
  );
};
