#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

__dirname="$(CDPATH= cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__rootDir="$(CDPATH= cd "$($__dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "..Running design token checks"
cd design-tokens
npm run paddingY:verify
npm run build
cd ${__rootDir}
echo "..Running aries-site checks"
cd aries-site
echo "....Linting checks for aries-site"
npm run lint-fix
cd ${__rootDir}
echo "..Running aries-core checks"
cd aries-core
echo "....Linting checks for aries-core"
npm run lint-fix
cd ${__rootDir}
echo "Pre-commit checks completed."
