#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "..Running design token checks"
pnpm --filter hpe-design-tokens run test
pnpm --filter hpe-design-tokens run paddingY:verify
pnpm --filter hpe-design-tokens run build

echo "..Running docs checks"
echo "....Linting checks for docs"
pnpm --filter docs run lint-fix

echo "..Running aries-core checks"
pnpm --filter "@shared/aries-core" run lint-fix

echo "Pre-commit checks completed."
