#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

__dirname="$(CDPATH= cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__rootDir="$(CDPATH= cd "$($__dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "..Running site checks"
cd site
echo "....Linting checks for site"
npm run lint-fix
cd ${__rootDir}
echo "..Running library checks"
cd library
echo "....Linting checks for library"
npm run lint-fix
cd ${__rootDir}
echo "Pre-commit checks completed."
