name: Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install latest dependencies
        run: yarn ugprade
        working-directory: aries-site
      - name: Build aries-site
        run: yarn build --if-present
        working-directory: aries-site
