name: Chromatic Visual Tests
on:
  pull_request:
    types:
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - master
    paths:
      - .github/workflows/chromatic-label.yml
      - .github/workflows/chromatic-run.yml
      - .github/workflows/chromatic.yml
      - apps/docs/src/examples/templates/**
      - packages/hpe-design-tokens/package.json
      - packages/hpe-design-tokens/src/**
      - packages/hpe-design-tokens/tokens/**
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - shared/aries-core/.storybook/**
      - shared/aries-core/babel.config.js
      - shared/aries-core/package.json
      - shared/aries-core/src/**
      - shared/aries-core/tsconfig.json
      - shared/aries-core/webpack.config.js
      - shared/hooks/package.json
      - shared/hooks/src/**
      - shared/hooks/tsconfig.build.esm.json
      - shared/hooks/tsconfig.json
  push:
    branches:
      - master
    paths:
      - .github/workflows/chromatic-label.yml
      - .github/workflows/chromatic-run.yml
      - .github/workflows/chromatic.yml
      - apps/docs/src/examples/templates/**
      - packages/hpe-design-tokens/package.json
      - packages/hpe-design-tokens/src/**
      - packages/hpe-design-tokens/tokens/**
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - shared/aries-core/.storybook/**
      - shared/aries-core/babel.config.js
      - shared/aries-core/package.json
      - shared/aries-core/src/**
      - shared/aries-core/tsconfig.json
      - shared/aries-core/webpack.config.js
      - shared/hooks/package.json
      - shared/hooks/src/**
      - shared/hooks/tsconfig.build.esm.json
      - shared/hooks/tsconfig.json

permissions:
  contents: read

concurrency:
  group: chromatic-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  chromatic:
    if: >-
      github.event_name == 'push' ||
      (github.event.pull_request.draft == false &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      contains(github.event.pull_request.labels.*.name, 'run-chromatic'))
    uses: ./.github/workflows/chromatic-run.yml
    with:
      branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
      ref: ${{ github.event.pull_request.head.sha || github.sha }}
      sha: ${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit
