name: End-to-End Tests
on: pull_request

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Use node.js
        uses: actions/setup-node@v1
      - name: Install modules
        run: npm install
      - run: npm run build --if-present
        working-directory: ./aries-site
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: 'chrome ./aires-site/src/tests'
