name: CI

on:
  pull_request:
    branches: 
      - master
    types: [closed] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull request merged
      if: github.event.pull_request.merged == true
      run: echo merged
