name: Sync Figma variables to tokens
on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Which branch to update
        options:
          - master
  schedule:
    # Run this workflow everyday at 16.00 UTC
    - cron: '0 16 * * *'
jobs:
  sync-figma-to-tokens:
    runs-on: ubuntu-latest
    permissions:
      # Need to be able to create new branches and commits
      contents: write
      pull-requests: write
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.x'

      - name: Set NPM version
        run: npm install -g npm@9.5.1

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Upgrade stable branch dependencies
        run: yarn upgrade grommet && yarn upgrade grommet-icons

      - name: Install dependencies
        run: yarn install

      - name: Sync variables in Figma file to tokens
        run: yarn sync-figma-to-tokens -- --output tokens
        working-directory: design-tokens
        env:
          FILE_KEY_PRIMITIVE: ${{ secrets.GH_ACTION_FIGMA_FILE_KEY_PRIMITIVE }}
          FILE_KEY_SEMANTIC: ${{ secrets.GH_ACTION_FIGMA_FILE_KEY_SEMANTIC }}
          FILE_KEY_COMPONENT: ${{ secrets.GH_ACTION_FIGMA_FILE_KEY_COMPONENT }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_ACTION_VARIABLES_SYNC_FIGMA_TOKEN }}
          FIGMA_COLOR_COLLECTION_KEY: ${{ secrets.GH_ACTION_FIGMA_COLOR_COLLECTION_KEY }}
          FIGMA_DIMENSION_COLLECTION_KEY: ${{ secrets.GH_ACTION_FIGMA_DIMENSION_COLLECTION_KEY }}
          FIGMA_PRIMITIVES_COLLECTION_KEY: ${{ secrets.GH_ACTION_FIGMA_PRIMITIVES_COLLECTION_KEY }}
          FIGMA_GLOBAL_COLLECTION_KEY: ${{ secrets.GH_ACTION_FIGMA_GLOBAL_COLLECTION_KEY }}
      - name: Format token files with prettier
        run: yarn prettier tokens --write
        working-directory: design-tokens
      - name: Build site search for pre-commit linting
        run: yarn build-search
        working-directory: aries-site
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update tokens from Figma
          title: Update tokens from Figma
          body: 'Update tokens from Figma from tokens files'
          base: ${{ github.event.inputs.branch }}
          branch: update-tokens
