name: Update design-tokens-stable
on:
  push:
    branches:
      - design-tokens-v2
    paths:
      - design-tokens/**

jobs:
  update-design-tokens-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.x'

      - name: Set NPM version
        run: npm install -g npm@9.5.1

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install
        working-directory: design-tokens

      - name: Build
        run: yarn build
        working-directory: design-tokens
      - name: Update design-tokens-stable
        run: |
          git config --global user.name "Grommet Community Bot"
          git config --global user.email "grommet@hpe.com"
          yarn release-stable
        working-directory: design-tokens
        env:
          GH_TOKEN: ${{ secrets.GH_ACTION_ACCESS_TOKEN }}
